apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "danswer-stack.fullname" . }}
  labels:
    {{- include "danswer-stack.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
{{- end }}
