{{- if and .Values.persistence.dynamic.enabled (not .Values.persistence.dynamic.existingClaim)}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "danswer-stack.fullname" . }}-dynamic
  labels:
    {{- include "danswer-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.dynamic.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.dynamic.size | quote }}
  {{- with .Values.persistence.dynamic.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}