apiVersion: v1
kind: Secret
metadata:
  name: {{ include "danswer-stack.fullname" . }}
  labels:
    {{- include "danswer-stack.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: '{{ $value | b64enc }}'
{{- end }}
