apiVersion: v1
kind: Service
metadata:
  name: {{ include "danswer-stack.fullname" . }}-vespa
  labels:
    {{- include "danswer-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: vespa-tenant-port
      protocol: TCP
      port: 19070
      targetPort: 19070
    - name: vespa-tenant-port-2
      protocol: TCP
      port: 19071
      targetPort: 19071
    - name: vespa-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    {{- include "danswer-stack.selectorLabels" . | nindent 4 }}
