{{- if and .Values.persistence.api.dynamic.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "danswer-stack.fullname" . }}-bg-dynamic
  labels:
    {{- include "danswer-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.background.dynamic.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.background.dynamic.size | quote }}
  {{- with .Values.persistence.background.dynamic.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}